apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data: 
  mysql_usermgmt.sql: |-
    DROP DATABASE IF EXISTS notes_app;
    CREATE DATABASE notes_app; 
  mysql-server: mysql-svc    # The name of mysql service
  mysql-database-name: notes_app     # The name of the database used by the demo app
  mysql-user-username: root     # A new created user for the demo app 