apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
spec:
  selector:
    app: mysql 
  ports: 
    - port: 3306  
  clusterIP: None # This means we are going to use Pod IP    

  #type: NodePort
  #ports:
  #- nodePort: 30171
  #  port: 3306
  #  protocol: TCP
  #  targetPort: 3306