apiVersion: v1
kind: Service
metadata:
  name: notesapp-javapi-svc
  labels: 
    app: notesapp-javapi
spec: 
  type: NodePort 
  selector: 
    app: notesapp-javapi
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000