---
- hosts: cd-servers
  tasks:
    - name: Establish connection to dockerhub
      shell: docker login -u youssef.baroudi@gmail.com -p Hakima.123  https://index.docker.io/v1/
    
    # Copying the .env to docker-server.
    - name: "copying .env with playbook to docker-server"
      copy:
        src: .env ?
        dest: /tmp/springboot-deployment.yml /home/.....
    - name: "docker-compose-java-mysql-api.yml with playbook to docker-server"
      copy:
        src: docker-compose-java-mysql-api.yml
        dest: /tmp/docker-compose-java-mysql-api.yml ?

    - name: Run the container using the docker-compose tool
      shell: docker-compose -f docker-compose-java-mysql-api.yml -p javamysqlapi down --remove-orphans && docker-compose -f docker-compose-java-mysql-api.yml --env-file .env config && docker-compose -f docker-compose-java-mysql-api.yml --env-file .env -p javamysqlapi up -d
---